language: cpp
compiler: gcc
# Sudo is required for non-standard packages
sudo: true
dist: trusty
addons:
  apt:
    sources:
    - sourceline: 'ppa:kzemek/boost'
    packages:
    - liblua5.1-0
    - liblua5.1-0-dev
    - libprotobuf-dev
    - libsqlite3-dev
    - protobuf-compiler
    - shapelib
    - libshp-dev
    - libboost1.58-dev
    - libboost-program-options1.58
    - libboost-filesystem1.58-dev
    - libboost-system1.58
script:
  - make -j2
